import 'package:flutter/foundation.dart';
import 'package:get/get.dart';
import 'package:dart_openai/dart_openai.dart';
import 'dashboard_controller.dart';

class AIController extends GetxController {

  final String _apiKey = " KEY";

  var isLoading = false.obs;
  var messages = <Map<String, String>>[].obs;
  var categoryAdvice = "Tap for expert category analysis ✨".obs;
  var isAnalysisStarted = false.obs;
  
  @override
  void onInit() {
    super.onInit();
    OpenAI.apiKey = _apiKey;
  }

  Future<void> sendMessage(String text, {bool isAutoGenerated = false}) async {
    if (text.isEmpty) return;

    final dashboard = Get.find<DashboardController>();
    String systemContext = "You are a financial advisor. User has spent ${dashboard.totalExpense.value} of ${dashboard.monthlyBudget.value} SAR.";

    if (!isAutoGenerated) {
      messages.add({"role": "user", "text": text});
    }

    isLoading.value = true;
    try {
      List<OpenAIChatCompletionChoiceMessageModel> chatMessages = [
        OpenAIChatCompletionChoiceMessageModel(
          role: OpenAIChatMessageRole.system,
          content: [OpenAIChatCompletionChoiceMessageContentItemModel.text(systemContext)],
        ),
        ...messages.map((m) => OpenAIChatCompletionChoiceMessageModel(
          role: m['role'] == 'user' ? OpenAIChatMessageRole.user : OpenAIChatMessageRole.assistant,
          content: [OpenAIChatCompletionChoiceMessageContentItemModel.text(m['text']!)],
        )).toList(),
      ];

      OpenAIChatCompletionModel completion = await OpenAI.instance.chat.create(
        model: "gpt-3.5-turbo", // الأمر الفعلي لإرسال الطلب عبر الإنترنت إلىOpenAI باستخدام موديل gpt-3.5-turbo
        messages: chatMessages,
      );

      messages.add({"role": "ai", "text": completion.choices.first.message.content!.first.text!});
    } catch (e) {
      messages.add({"role": "ai", "text": "Communication Error: $e"});
    } finally {
      isLoading.value = false;
    }
  }

  // --- ( dashboard_screen.dart) ---
  Future<void> generateFinancialAdvice() async {
    final dashboard = Get.find<DashboardController>();
    double percent = (dashboard.totalExpense.value / dashboard.monthlyBudget.value) * 100;

    String prompt = "I've used ${percent.toStringAsFixed(1)}% of my budget (${dashboard.totalExpense.value} SAR). Give me ONE very short personalized advice.";
    await sendMessage(prompt, isAutoGenerated: true);
  }

  // --- ( analytics_screen.dart) ---
  Future<void> analyzeCategorySpending(List<Map<String, dynamic>> categoryData) async {
    if (categoryData.isEmpty || isAnalysisStarted.value) {
      return;
    }

    isAnalysisStarted.value = true; // قفل العملية لمنع التكرار والانهيار

    String breakdown = categoryData.map((c) => "${c['categoryName']}: ${c['amount']} SAR").join(", ");
    String prompt = """
      You are a financial analyst. Analyze this user spending: $breakdown.
      If spending in any category is unusually high, provide a sharp warning/alert.
      Otherwise, provide a specific saving tip for the top category.
      Keep it very brief (max 10 words).
    """;

    isLoading.value = true;
    try {
      final completion = await OpenAI.instance.chat.create(
        model: "gpt-3.5-turbo",
        messages: [
          OpenAIChatCompletionChoiceMessageModel(
            role: OpenAIChatMessageRole.user,
            content: [OpenAIChatCompletionChoiceMessageContentItemModel.text(prompt)],
          ),
        ],
      ).timeout(const Duration(seconds: 15)); // منع الانتظار الطويل الذي يكسر الاتصال

      categoryAdvice.value = completion.choices.first.message.content!.first.text!;
    } catch (e) {
      debugPrint("AI Logic Error: $e");
      categoryAdvice.value = "Connect to internet to get AI insights.";
      isAnalysisStarted.value = false; // السماح بالمحاولة مرة أخرى
    } finally {
      isLoading.value = false;
    }
  }

}